---

- name: Install Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openssh-clients
  when: ansible_os_family == "RedHat"

# Configure users that will initiate hostbased ssh
- include: config_user_ssh.yml

# Allow incoming hostbased ssh
- include: config_sshd.yml
